apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-jolu
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-jolu
  template:
    metadata:
      labels:
        app: flask-jolu
    spec:
      containers:
      - name: flask-container-jolu
        image: jonasgroetschel/jolu-projet:latest
        ports:
        - containerPort: 7897