apiVersion: v1
kind: Service
metadata:
  name: flask-service-jolu
spec:
  selector:
    app: flaskjl
  type: LoadBalancer
  ports:
  - name: flask-service-port
    protocol: TCP
    port: 80
    targetPort: 5000