apiVersion: v1
kind: Service
metadata:
  name: flask-service-jolu
spec:
  selector:
    app.kubernetes.io/name: flask-jolu
  type: LoadBalancer
  ports:
  - name: flask-service-port
    protocol: TCP
    port: 7897
    targetPort: 5000