env:
  image: "jonasgroetschel/jolu-projet:latest"

name: Build projetKube

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install flask 
        run: pip install Flask

      - name: azure login
        run: |
          az login -u ${{ secrets.AZURE_CLIENT_ID }} --service-principal -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_CLUSTER_NAME }}

      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build Image and Push
        run: |
          docker build -t $image .
          docker tag $image $image
          docker push $image
      
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment flask || kubectl apply -f deployment.yaml 
          kubectl apply -f service.yaml 
        
      